### ISSUE TITLE
Installation Docs

### ISSUE THREAD

**Issue by oojacoboo** [shustrik/vscode-symfony-plugin#1]
First of all, I wanted to say, this is awesome and much needed!

Can you update the docs a bit for installation?  Also, what is needed for testing to get this plugin published?

**Comment by shustrik** [comment]
I'll try to update docs on this week and add some information about testing.

**Comment by shustrik** [comment]
@oojacoboo 
[Install Documentation](https://github.com/shustrik/vscode-symfony-plugin/tree/master/client)

Also please test autocomplete in configuration files and in method  get  in ContainerInterface object
