### ISSUE TITLE
No .vsix file to install ?

### ISSUE THREAD

**Issue by teol** [shustrik/vscode-symfony-plugin#4]
Hi,

This extension looks cool so I wanted to install it but I couldn't. There's no .vsix file in the repo, as needed by VS Code to install it.
I even tried to rename the .zip of the repo to .vsix but I still can't install it.

I am missing something? How to install it?

Thank you,
Have a good day

**Comment by shustrik** [comment]
@teol Hi. Sorry for the late reply.  I'll try to add .vsix file at this week

**Comment by teol** [comment]
No problem, thanks

**Comment by shustrik** [comment]
@teol  I Updated Readme.
https://github.com/shustrik/vscode-symfony-plugin/raw/master/vscode-symfony-client-0.1.2.vsix

If you have any questions about plugin or face any issue, please let me know. I tested plugin only on my project.

**Comment by teol** [comment]
Thanks :).
Seems to work, I will use it on a daily basis and create new issues if needed.
